const HUYEN_TIEN_LEVEL = 756;
const HUYEN_TIEN_LAST_LEVEL = 876;
const HUYEN_TIEN_EXP = 26990;
const KIM_TIEN_lEVEL = 936;
const KIM_TIEN_LAST_LEVEL = 1101;
const KIM_TIEN_EXP = 25800;
const TIEN_QUAN_EXP = 24570;
const TIEN_QUAN_LEVEL = 1201;
const TIEN_QUAN_LAST_LEVEL = 1500;
const EXP_PER_DAY = 50000;
export {
	HUYEN_TIEN_LEVEL,
	HUYEN_TIEN_LAST_LEVEL,
	HUYEN_TIEN_EXP,
	KIM_TIEN_lEVEL,
	KIM_TIEN_LAST_LEVEL,
	KIM_TIEN_EXP,
	TIEN_QUAN_EXP,
	TIEN_QUAN_LEVEL,
	TIEN_QUAN_LAST_LEVEL,
	EXP_PER_DAY,
};
